//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "email_embedding")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub email_id: String,
    #[sea_orm(column_type = "custom(\"vector\")")]
    pub embedding: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
