//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod auto_cleanup_setting;
pub mod email_embedding;
pub mod email_training;
pub mod inbox_settings;
pub mod processed_daily_summary;
pub mod processed_email;
pub mod sea_orm_active_enums;
pub mod system_email_rule;
pub mod user;
pub mod user_account_access;
pub mod user_email_rule;
pub mod user_token_usage_stat;
