//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::auto_cleanup_setting::Entity as AutoCleanupSetting;
pub use super::email_embedding::Entity as EmailEmbedding;
pub use super::email_training::Entity as EmailTraining;
pub use super::processed_daily_summary::Entity as ProcessedDailySummary;
pub use super::processed_email::Entity as ProcessedEmail;
pub use super::user::Entity as User;
pub use super::user_account_access::Entity as UserAccountAccess;
pub use super::user_email_rule::Entity as UserEmailRule;
pub use super::user_token_usage_stat::Entity as UserTokenUsageStat;
