//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "processed_email")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: i32,
    pub processed_at: DateTimeWithTimeZone,
    pub ai_answer: String,
    pub category: String,
    #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
    pub history_id: Decimal,
    pub extracted_tasks: Option<Vec<Json>>,
    pub is_read: bool,
    pub due_date: Option<DateTime>,
    pub tasks_done: bool,
    pub has_new_reply: bool,
    pub ai_confidence: String,
    pub thread_id: String,
    pub is_thread: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
