//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use super::sea_orm_active_enums::SubscriptionStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub email: String,
    pub subscription_status: SubscriptionStatus,
    pub last_successful_payment_at: Option<DateTimeWithTimeZone>,
    pub last_payment_attempt_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub setup_completed: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auto_cleanup_setting::Entity")]
    AutoCleanupSetting,
    #[sea_orm(has_many = "super::custom_email_rule::Entity")]
    CustomEmailRule,
    #[sea_orm(has_many = "super::default_email_rule_override::Entity")]
    DefaultEmailRuleOverride,
    #[sea_orm(has_many = "super::processed_daily_summary::Entity")]
    ProcessedDailySummary,
    #[sea_orm(has_many = "super::processed_email::Entity")]
    ProcessedEmail,
    #[sea_orm(has_one = "super::user_account_access::Entity")]
    UserAccountAccess,
    #[sea_orm(has_many = "super::user_token_usage_stat::Entity")]
    UserTokenUsageStat,
}

impl Related<super::auto_cleanup_setting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AutoCleanupSetting.def()
    }
}

impl Related<super::custom_email_rule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomEmailRule.def()
    }
}

impl Related<super::default_email_rule_override::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DefaultEmailRuleOverride.def()
    }
}

impl Related<super::processed_daily_summary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProcessedDailySummary.def()
    }
}

impl Related<super::processed_email::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProcessedEmail.def()
    }
}

impl Related<super::user_account_access::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAccountAccess.def()
    }
}

impl Related<super::user_token_usage_stat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTokenUsageStat.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
